apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bq0zybxnv-nodejs 
  janus-idp.io/tekton: bq0zybxnv-nodejs
  backstage.io/kubernetes-id: bq0zybxnv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bq0zybxnv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml