apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bq0zybxnv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bq0zybxnv-nodejs 
  name: bq0zybxnv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bq0zybxnv-nodejs 
